USE master
GO
CREATE DATABASE DataSocial
GO

USE DataSocial
GO

CREATE TABLE ACCOUNT
(
    UID VARCHAR(30) NOT NULL,
    ID VARCHAR(20),
    PASS VARCHAR(20)
    CONSTRAINT PK_ACCOUNT PRIMARY KEY (ID)
)
CREATE TABLE PROFILE
(
    UIDuser VARCHAR(30) NOT NULL,
    NAME VARCHAR(20),
    AVATAR IMAGE DEFAULT NULL
    CONSTRAINT PK_PROFILE PRIMARY KEY (UIDuser)
)

ALTER TABLE dbo.ACCOUNT ADD CONSTRAINT FK_ACCOUNT FOREIGN KEY (UID) REFERENCES dbo.PROFILE(UIDuser)

--CSDSCSDCSDCSDC

CREATE TABLE FRIEND
(
	UID1 VARCHAR(30) NOT NULL,
	UID2 VARCHAR(30) NOT NULL
	CONSTRAINT FK_FRIEND1 FOREIGN KEY (UID1) REFERENCES dbo.PROFILE(UIDuser),
	CONSTRAINT FK_FRIEND2 FOREIGN KEY (UID2) REFERENCES dbo.PROFILE(UIDuser)
)

-- svsdvsdvsdv

CREATE TABLE POST
(
	IDPOST VARCHAR(30) PRIMARY KEY,
	IDUSER VARCHAR(30),
	LIKED INTEGER,
	CONTENT TEXT,
	IMAGE IMAGE DEFAULT NULL,
	TIME DATETIME DEFAULT GETDATE()
	CONSTRAINT FK_POST FOREIGN KEY (IDUSER) REFERENCES dbo.PROFILE(UIDuser)
)

CREATE TABLE COMMENT
(
	IDcomment VARCHAR(30) PRIMARY KEY,
	IDPOST VARCHAR(30),
	CONTENT TEXT,
	TIME DATETIME DEFAULT GETDATE()
	CONSTRAINT FK_COMMENT FOREIGN KEY (IDPOST) REFERENCES dbo.POST(IDPOST)
)

--MESSENGER

CREATE TABLE MessengerBox
(
	IDmessengerbox VARCHAR(30) PRIMARY KEY
)

CREATE TABLE MESSENGER
(
	IDmessenger VARCHAR(30)PRIMARY KEY,
	IDmessengerbox VARCHAR(30),
	UIDsend VARCHAR(30) NOT NULL,
	Content TEXT,
	Image IMAGE DEFAULT NULL,
	TIME DATETIME DEFAULT GETDATE()
	CONSTRAINT FK_MESSENGER_MessengerBox FOREIGN KEY (IDmessengerbox) REFERENCES dbo.MessengerBox(IDmessengerbox),
	CONSTRAINT FK_MESSENGER_PROFILE FOREIGN KEY (UIDsend) REFERENCES dbo.PROFILE(UIDuser)

)